name: 🐛 Отчет об ошибке (Bug Report)
description: Сообщить об ошибке в работе Discord-бота
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Описание проблемы
      description: Что именно произошло?
      placeholder: Подробное описание бага...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Шаги для воспроизведения
      description: Какая команда или действие привели к ошибке?
      placeholder: /command, /server, /steamsl...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Логи бота (Console / journalctl)
      description: Прикрепите фрагмент лога с ошибкой
      render: text
