name: Auto Assign Issues and PRs

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

permissions:
  issues: write
  pull-requests: write

jobs:
  auto-assign:
    name: Assign Maintainer
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue or PR
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number || github.event.pull_request.number }}
          assignees: '${{ github.repository_owner }}'
